apiVersion: v1
kind: Service
metadata:
  name: discovery-server-service
  labels:
    app: discovery-server-service
spec: 
  selector:
    app: esp-discovery-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30000